[data]
    email = "is3mansour@gmail.com"
[diff]
    command = "code"
    args = ["--diff", "{{ .Destination }}", "{{ .Target }}"]
[edit]
    command = "code"
    args = ["--wait"]
[git]
    autoCommit = true
    autoPush = true
[merge]
    command = "nvim"
    args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]

encryption = "gpg"
[gpg]
    recipient = "712B106A06F5ACEC"
    symmetric = false
