[data]
    email = "me@imansour.net"
[diff]
    command = "meld"
    args = ["--diff", "{{ .Destination }}", "{{ .Target }}"]
[edit]
    command = "code"
    args = ["--wait"]
[git]
    autoCommit = true
    autoPush = true
[merge]
    command = "nvim"
    args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]

encryption = "gpg"
[gpg]
    recipient = "..."